const WHATSAPP_URL =
  'https://wa.me/923002121224?text=Hello%20Kamran%20Shawls%2C%20I%27d%20like%20to%20know%20more%20about%20your%20collection.';

export const WHATSAPP_LINK = WHATSAPP_URL;

export const PRODUCTS = [
  {
    id: 'ivory-pashmina',
    category: 'pashmina',
    tag: '100% Pure Pashmina',
    name: 'Ivory Pashmina Wrap',
    desc: 'Featherlight winter shawl in undyed virgin ivory cashmere. Finished with traditional hand-rolled eyelash fringes for natural warmth without bulk.',
    price: 'PKR 6,500',
    dimensions: '2.25m × 1.15m',
    weight: '180 grams (Featherlight)',
    origin: 'Himalayan Foothills',
    weave: 'Diamond Twill (Chashm-e-Bulbul)',
    warmth: 'High Warmth (Winter & Autumn)',
    enquiryText: 'Ivory%20Pashmina%20Wrap',
    visual: 'pashmina',
    featured: true,
  },
  {
    id: 'swati-shawl',
    category: 'wool',
    tag: 'Handspun Swati Valley Wool',
    name: 'Swati Heritage Shawl',
    desc: 'Heavyweight mountain wool shawl in deep oxblood with intricate gold-thread jacquard border weave. Traditional ceremonial winter chadar.',
    price: 'PKR 12,900',
    dimensions: '2.5m × 1.35m',
    weight: '580 grams (Heavyweight Chadar)',
    origin: 'Swat Valley, Khyber Pakhtunkhwa',
    weave: 'Twill Weave with Zari Border',
    warmth: 'Maximum Winter Warmth',
    enquiryText: 'Swati%20Heritage%20Shawl',
    visual: 'swati',
    featured: true,
  },
  {
    id: 'charcoal-shatoosh',
    category: 'shatoosh',
    tag: 'Pure Grade Shatoosh Weft',
    name: 'Charcoal Shatoosh Shawl',
    desc: 'Our crown weave. Incomparably soft, gossamer-fine natural fibers with subtle dark self-stripes. Easily passes through a finger ring.',
    price: 'PKR 18,500',
    dimensions: '2.4m × 1.2m',
    weight: '140 grams (Ultra-Fine)',
    origin: 'High Altitude Northern Valleys',
    weave: 'Ring-Grade Gossamer Weft',
    warmth: 'Extreme Thermal Efficiency',
    enquiryText: 'Charcoal%20Shatoosh%20Shawl',
    visual: 'shatoosh',
    featured: true,
  },
  {
    id: 'rose-silk',
    category: 'silk',
    tag: 'Mulberry Silk & Fine Wool',
    name: 'Rose Silk Evening Stole',
    desc: 'Lustrous rose-gold silk blended with fine Australian merino wool. Soft, fluid drape with a radiant sheen suited for weddings and evening gatherings.',
    price: 'PKR 4,800',
    dimensions: '2.0m × 0.85m',
    weight: '210 grams (Lightweight)',
    origin: 'Artisan Loom Guilds',
    weave: 'Satin Silk Weft Interlace',
    warmth: 'Mild to Moderate Warmth',
    enquiryText: 'Rose%20Silk%20Evening%20Stole',
    visual: 'silk',
    featured: true,
  },
  {
    id: 'charcoal-merino',
    category: 'wool',
    tag: 'Australian Merino Wool',
    name: 'Charcoal Merino Wrap',
    desc: 'A minimal modern everyday wrap in 100% fine micron merino wool. Soft against sensitive skin, non-itchy, and completely unpatterned.',
    price: 'PKR 5,200',
    dimensions: '2.1m × 1.0m',
    weight: '290 grams (Medium Weight)',
    origin: 'Artisanal Loom House',
    weave: 'Plain Weave Soft Brushed',
    warmth: 'Moderate to High Warmth',
    enquiryText: 'Charcoal%20Merino%20Wrap',
    visual: 'merino',
    featured: false,
  },
  {
    id: 'indigo-blockprint',
    category: 'cotton',
    tag: 'Hand Block-Print Cotton',
    name: 'Indigo Block-Print Shawl',
    desc: 'Hand-carved wooden block print on breathable combed cotton using natural indigo and madder root dyes. Ideal for all-season draping.',
    price: 'PKR 3,600',
    dimensions: '2.3m × 1.1m',
    weight: '240 grams (All Season)',
    origin: 'Heritage Block Print Ateliers',
    weave: 'Combed Cotton Canvas',
    warmth: 'All-Season Cool Wrap',
    enquiryText: 'Indigo%20Block-Print%20Shawl',
    visual: 'blockprint',
    featured: false,
  },
  {
    id: 'sozni-pashmina',
    category: 'pashmina',
    tag: 'Sozni Needlework Pashmina',
    name: 'Kashmiri Sozni Embroidered Wrap',
    desc: 'Pure Pashmina canvas adorned with delicate hand-stitched needlework along all four borders. Crafted over 45 days by master needle-smiths.',
    price: 'PKR 24,000',
    dimensions: '2.3m × 1.15m',
    weight: '220 grams (Embroidered)',
    origin: 'Kashmir Valley Guilds',
    weave: 'Fine Twill with Sozni Needlework',
    warmth: 'High Luxury Warmth',
    enquiryText: 'Kashmiri%20Sozni%20Embroidered%20Wrap',
    visual: 'pashmina',
    featured: true,
  },
  {
    id: 'honey-gold-swati',
    category: 'wool',
    tag: 'Swat Valley Wool',
    name: 'Honey Gold Swati Chadar',
    desc: 'Warm honey-ochre sheep wool chadar featuring geometric hand-loomed border strips and hand-twisted woolen tassels.',
    price: 'PKR 14,500',
    dimensions: '2.6m × 1.4m',
    weight: '620 grams (Traditional Chadar)',
    origin: 'Upper Swat Valley',
    weave: 'Dense Handloom Weft',
    warmth: 'Heavy Winter Shield',
    enquiryText: 'Honey%20Gold%20Swati%20Chadar',
    visual: 'swati',
    featured: false,
  },
  {
    id: 'midnight-pashmina',
    category: 'pashmina',
    tag: 'Double-Twill Pashmina',
    name: 'Midnight Slate Pashmina Stole',
    desc: 'Rich charcoal-slate pashmina woven in double-twill for enhanced drape and structured elegance on blazers or formal sherwanis.',
    price: 'PKR 7,200',
    dimensions: '2.1m × 0.9m',
    weight: '195 grams',
    origin: 'Himalayan Foothills',
    weave: 'Double-Twill Cashmere',
    warmth: 'High Winter Warmth',
    enquiryText: 'Midnight%20Slate%20Pashmina%20Stole',
    visual: 'merino',
    featured: false,
  },
];

export const MATERIALS_GUIDE = [
  {
    name: 'Pure Pashmina',
    micron: '12 - 15 Microns',
    feel: 'Featherlight & Cloud-Soft',
    warmth: '9.5 / 10',
    warmthPercent: 95,
    idealFor: 'Formal Winter Events, Weddings & Luxury Everyday Drape',
    description: 'Harvested exclusively from the underbelly of high-altitude Himalayan mountain goats. Unrivalled insulation despite being almost weightless.',
  },
  {
    name: 'Royal Shatoosh',
    micron: '9 - 11 Microns',
    feel: 'Gossamer Fine & Weightless',
    warmth: '10 / 10',
    warmthPercent: 100,
    idealFor: 'Heirloom Keepsakes, Connoisseurs & Deep Freezing Temperatures',
    description: 'The finest natural animal fiber known to mankind. King of weaves with supreme thermal density that easily passes through a small ring.',
  },
  {
    name: 'Swati Mountain Wool',
    micron: '24 - 28 Microns',
    feel: 'Substantial, Crisp & Structured',
    warmth: '9.0 / 10',
    warmthPercent: 90,
    idealFor: 'Men’s Traditional Chadars, Heavy Mountain Frost & Formal Occasions',
    description: 'Spun from hardy mountain sheep wool in Swat Valley. Famous for its thick density, weather resistance, and ornate border weaves.',
  },
  {
    name: 'Silk-Wool Blends',
    micron: '16 - 19 Microns',
    feel: 'Lustrous, Fluid & Silky Sheen',
    warmth: '7.5 / 10',
    warmthPercent: 75,
    idealFor: 'Evening Dinners, Festive Parties & Transitional Seasons',
    description: 'Combines the natural thermal trap of fine merino wool with the vibrant, light-catching sheen of pure mulberry silk threads.',
  },
];

export const CRAFT_DETAILED_STEPS = [
  {
    number: '01',
    stage: 'High-Altitude Fiber Sourcing',
    title: 'Traveling Directly to Northern Weavers',
    desc: 'We bypass factory middlemen and industrial clearinghouses. Every year, our curators travel into mountain valleys to source raw combed fleeces and small artisan loom runs.',
    details: ['Direct fair-compensation to weavers', 'Inspection of raw yarn micron count', 'Zero synthetic polyester blends accepted'],
  },
  {
    number: '02',
    stage: 'Artisanal Hand-Spinning',
    title: 'Spun on Wooden Charkha Wheels',
    desc: 'Delicate high-altitude fleece cannot withstand harsh industrial automated spinners. Skilled village craftswomen spin the fiber by hand to maintain the natural elasticity and warmth.',
    details: ['Preserves natural air pockets between fibers', 'Gentle yarn tension prevents breakage', 'Traditional wooden wheel craftsmanship'],
  },
  {
    number: '03',
    stage: 'Handloom Weaving',
    title: 'Interlaced Thread by Thread',
    desc: 'Each shawl is painstakingly woven on traditional wooden pit looms or frame looms. A master weaver may spend anywhere from 4 to 45 days completing a single shawl.',
    details: ['Intricate Boteh (paisley) and Zari borders', 'High warp-to-weft thread count', 'Distinctive organic handloom selvage edge'],
  },
  {
    number: '04',
    stage: 'Natural Botanical Dyeing',
    title: 'Gentle Mineral & Vegetable Pigments',
    desc: 'To preserve the soft, sensitive fleece, yarns are immersed in warm dye vats infused with natural walnut husks, madder roots, indigo, and gentle botanical extracts.',
    details: ['Colorfast, non-fading hues', 'Chemical-free gentle treatment', 'Rich, deep organic color tones'],
  },
  {
    number: '05',
    stage: 'Hand-Finishing & Needlework',
    title: 'Rolled Fringes & Sozni Needles',
    desc: 'Edges are hand-twisted and knotted into traditional eyelashes. For embroidered pieces, master needle-smiths use single-strand silk threads to hand-stitch ornate floral motifs.',
    details: ['Hand-rolled and knotted fringes', 'Optional Sozni & Tilla needlework', 'Clean, refined reverse-side finish'],
  },
  {
    number: '06',
    stage: '4-Point Nathia Gali Inspection',
    title: 'In-Store Verification Before Display',
    desc: 'Every shawl entering our Nathia Gali boutique is hand-examined under bright light: testing weight, checking weave uniformity, ensuring border alignment, and steam-pressing.',
    details: ['100% purity and weight verification', 'Gentle cedar press and protective packing', 'Direct nationwide tracked courier dispatch'],
  },
];

export const TESTIMONIALS = [
  {
    name: 'Sardar Hamza Khan',
    city: 'Islamabad',
    shawl: 'Swati Heritage Shawl in Oxblood',
    comment: 'The weight and border weave on this Swati chadar are extraordinary. It kept me warm during sub-zero Murree winters. Truly an authentic piece that you cannot find in regular city malls.',
    rating: 5,
  },
  {
    name: 'Dr. Ayesha Malik',
    city: 'Lahore (Defence)',
    shawl: 'Ivory Pashmina Wrap & Shatoosh Weft',
    comment: 'Ordered over WhatsApp with high-resolution video consultation. The curator showed me the texture up close. It arrived in Lahore in 2 days, beautifully pressed and incredibly soft.',
    rating: 5,
  },
  {
    name: 'Kamaluddin Farooqi',
    city: 'Karachi (Clifton)',
    shawl: 'Charcoal Shatoosh Shawl',
    comment: 'Kamran Shawls has been our family’s trusted shop whenever we visit Nathia Gali in the summer. Their pure shatoosh weave is featherlight yet shockingly warm. Supreme quality.',
    rating: 5,
  },
];

export const FAQS = [
  {
    question: 'How do I place an order without a standard website checkout?',
    answer: 'We operate on a personal boutique model. Simply click "Message on WhatsApp" or "Call Us" with the shawl you are interested in. Our curator in Nathia Gali will send you live photos, video previews, confirm dimensions, and arrange tracked courier delivery with payment upon receipt.',
  },
  {
    question: 'How can I verify that my Pashmina or Shatoosh is 100% pure?',
    answer: 'Pure Pashmina is featherlight (under 200g), instantly generates warmth when draped, has an organic matte sheen (not synthetic plastic shine), and displays an irregular handspun texture under magnification. Every shawl at Kamran Shawls is tested and backed by our shop’s reputation.',
  },
  {
    question: 'What is the nationwide delivery timeline across Pakistan?',
    answer: 'We dispatch via tracked express couriers (TCS / Leopard) directly from our shop. Deliveries to Islamabad/Rawalpindi take 1-2 business days; Lahore, Peshawar, and Karachi take 2-3 business days.',
  },
  {
    question: 'How should I wash and care for handwoven luxury shawls?',
    answer: 'We strongly recommend professional dry cleaning only. Store your shawl in breathable cotton bags with natural cedarwood balls to prevent moths. Never hang heavy wool shawls on wire hangers — fold them gently flat.',
  },
  {
    question: 'Do you offer customized gift boxes or bulk wedding orders?',
    answer: 'Yes! We frequently curate bespoke shawl boxes for winter weddings, family celebrations, and corporate gifts. Message us on WhatsApp to discuss custom packaging and bulk pricing.',
  },
];

export const STEPS = [
  {
    stage: '01. Sourcing',
    title: 'Visiting the Master Weavers',
    desc: 'We visit weavers and wholesale markets directly across mountain valleys and buy in small, curated batches.',
  },
  {
    stage: '02. Selection',
    title: 'Hand-Picking Pristine Fleeces',
    desc: 'Only shawls that pass our strict criteria for fiber micron, weave density, and finish make it into the shop.',
  },
  {
    stage: '03. Inspection',
    title: '4-Point In-Store Quality Check',
    desc: 'Each shawl is checked in Nathia Gali for warp tension, fringe perfection, and embroidery integrity.',
  },
  {
    stage: '04. Packaging',
    title: 'Cedar Press & Express Dispatch',
    desc: 'Every order is pressed by hand, packaged in protective covers, and dispatched nationwide via express courier.',
  },
];
